# Generated by Django 3.2.4 on 2021-08-29 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Header',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('image_default_name', models.CharField(max_length=100)),
                ('image_default_path', models.CharField(max_length=255)),
                ('image_event_name', models.CharField(max_length=100)),
                ('image_event_path', models.CharField(max_length=255)),
                ('created_at', models.DateField()),
                ('updated_at', models.DateField(null=True)),
            ],
        ),
    ]
