# Generated by Django 3.2.4 on 2021-08-29 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_category_categorypost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category_image_event',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='category_image_event_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
