# Generated by Django 3.2.4 on 2021-08-29 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_auto_20210829_1339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcolor',
            name='product_color_code',
            field=models.CharField(max_length=25),
        ),
    ]
