# Generated by Django 3.2.4 on 2021-08-30 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0007_alter_productcolor_product_color_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='header',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
