# Generated by Django 3.2.4 on 2021-08-31 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0009_auto_20210831_1533'),
    ]

    operations = [
        migrations.AlterField(
            model_name='header',
            name='updated_at',
            field=models.DateField(auto_now=True, null=True),
        ),
    ]
