# Generated by Django 3.2.4 on 2021-09-01 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0010_alter_header_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='header',
            name='created_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='header',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
