# Generated by Django 3.2.4 on 2021-09-02 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0012_bannertitle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='header',
            name='active',
            field=models.BooleanField(),
        ),
    ]
