# Generated by Django 3.2.4 on 2021-09-03 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0016_category_display_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorypost',
            name='created_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='categorypost',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='created_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='created_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_end',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_start',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='confirm_order_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='order',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='orderdetail',
            name='created_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='orderdetail',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='created_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='productcolor',
            name='created_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='productcolor',
            name='updated_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='productdetail',
            name='created_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='productdetail',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='created_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='productpromotion',
            name='created_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='productpromotion',
            name='product_promotion_end',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='productpromotion',
            name='product_promotion_start',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='productpromotion',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='productsize',
            name='created_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='productsize',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='producttype',
            name='created_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='producttype',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
