# Generated by Django 3.2.4 on 2021-09-06 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0018_categorypost_category_post_image_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorypost',
            name='category_post_content',
            field=models.TextField(),
        ),
    ]
