# Generated by Django 3.2.4 on 2021-09-15 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0021_auto_20210912_0817'),
    ]

    operations = [
        migrations.AddField(
            model_name='productdetail',
            name='product_in_stock',
            field=models.IntegerField(default=0),
        ),
    ]
