# Generated by Django 3.2.4 on 2021-09-15 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0022_productdetail_product_in_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_detail',
            field=models.TextField(),
        ),
    ]
