# Generated by Django 3.2.4 on 2021-09-19 13:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0023_alter_product_product_detail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productpromotion',
            name='event_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.event'),
        ),
    ]
