DISPLAY_TRUE = 1

DISPLAY_FALSE = 0

MESSAGE_POPUP_SUCCESS = 'Thành công.'

MESSAGE_POPUP_ERROR = 'Thất bại.'

CATEGORY_DISPLAY_TYPE_1 = 1

CATEGORY_DISPLAY_TYPE_2 = 2

CATEGORY_DISPLAY_TYPE_3 = 3

LIMIT_POST_IN_HOME_TYPE_1 = 4

LIMIT_POST_IN_HOME_TYPE_2 = 10

LIMIT_POST_IN_HOME_TYPE_3 = 5
